FROM ubuntu:24.04

# Set the working directory
WORKDIR /app

# Install dependencies
RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y curl git unzip xz-utils zip libglu1-mesa \
    openjdk-11-jdk wget clang cmake pkg-config ninja-build \
    libgtk-3-dev libstdc++6 ca-certificates

# Install Flutter
RUN wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.2-stable.tar.xz && \
    tar -xf flutter_linux_3.29.2-stable.tar.xz -C /usr/local/ && \
    rm flutter_linux_3.29.2-stable.tar.xz

ENV PATH="/usr/local/flutter/bin:${PATH}"

# Enable Flutter analytics and pre-cache dependencies
RUN flutter config --no-analytics && \
    flutter doctor && \
    flutter upgrade && \
    flutter precache

# Copy project files
COPY . /app

# Install project dependencies
RUN flutter pub get

# Build the app
RUN flutter build web

# Install nginx to serve the Flutter web app
RUN apt-get install -y nginx && \
    rm -rf /var/www/html && \
    mv /app/build/web /var/www/html

# Expose the default nginx port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
