CREATE TABLE Users (
    UserName NVARCHAR(450),
    Password NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(MAX) NOT NULL
);

CREATE TABLE URLs (
    Origin_URL NVARCHAR(450) PRIMARY KEY,
    Short_URL NVARCHAR(MAX) NOT NULL,
    user_id INT NOT NULL,
    Create_date DATETIME2(7) NOT NULL,
    Expired_date DATETIME2(7) NULL
);