version: '3.8'

services:
  web:
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["dotnet", "YourApp.dll"]