version: '1.0'

services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: aspnet_api
    ports:
      - "5254:80"
    volumes:
      - ./API:/app
    working_dir: /app
    command: ["dotnet", "run"]

  flutter:
    image: fischerscode/flutter:latest
    container_name: flutter_app
    ports:
      - "3000:3000"
    volumes:
      - ./Flutter:/app
    working_dir: /app
    command: ["flutter", "run", "-d", "web-server", "--web-port", "3000"]

  database: # SQL Server (Finished)
    image: mcr.microsoft.com/mssql/server
    container_name: mssql_database
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TranNguyenMinhPhuong11122003"
      ACCEPT_EULA: "Y"
    